# Generated by Django 3.2.5 on 2021-12-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_userinfo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
